### PR TITLE
fix(profile): move preferences into profile sub-nav tab

### LINKED ISSUE #46: bug: Preferences page should be a sub-nav tab inside /profile, not a separate route
## Problem

The `/preferences` page currently exists as a standalone top-level route (`src/app/(app)/preferences/page.tsx`) with its own entry in the desktop sidebar navigation. However, it should be a sub-nav tab inside the `/profile` page, consistent with how other profile-related settings (Personal, Password, Features) are organized.

### Current behavior
- `/preferences` is a separate route at the same level as `/dashboard`, `/transactions`, etc.
- It appears as its own item in the desktop sidebar nav (`app-shell.tsx`)
- On mobile, the profile page already links to `/preferences` as if it were a sub-page (with a `ChevronRight` card), creating an inconsistent navigation pattern

### Expected behavior
- Preferences (display settings) should be a tab inside the `/profile` page sub-nav, alongside Personal, Password, and Features
- The `/preferences` top-level route and its sidebar nav entry should be removed
- The mobile card link to `/preferences` on the profile page should be removed (since it will be accessible as a tab)

## Files involved
- `src/app/(app)/preferences/page.tsx` — to be removed
- `src/app/(app)/profile/page.tsx` — add "Preferences" tab with display settings content
- `src/components/app-shell.tsx` — remove Preferences from `NAV_ITEMS`

### PR DESCRIPTION
**Pull request by chrisgen19**
## Summary
- Moved Preferences from a standalone top-level route (`/preferences`) into the Profile page as a 4th sub-nav tab alongside Personal, Password, and Features
- Removed Preferences from the desktop sidebar navigation in `app-shell.tsx`
- Removed the mobile card link to `/preferences` on the profile page (now accessible as a tab)
- Deleted `src/app/(app)/preferences/page.tsx`

Closes #46

## Test plan
- [ ] Navigate to `/profile` — verify "Preferences" tab appears in the desktop sub-nav
- [ ] Click Preferences tab — verify day name toggle, format picker, and preview render correctly
- [ ] On mobile, verify all 4 sections (Personal, Password, Features, Preferences) render stacked
- [ ] Verify `/preferences` route no longer exists (should 404)
- [ ] Verify sidebar nav no longer shows Preferences as a top-level item

### CODE REVIEW

File: src/app/(app)/profile/page.tsx [hunk 1]
```diff
@@ -166,6 +165,7 @@ export default function ProfilePage() {
     { id: "personal", label: "Personal Information", icon: User },
     { id: "password", label: "Change Password", icon: Lock },
     { id: "features", label: "Features", icon: Sparkles },
+    { id: "preferences", label: "Preferences", icon: Settings2 },
```
Comment (chrisgen19) [inline src/app/(app)/profile/page.tsx]: Moving Preferences into Profile makes sense, but deleting the standalone route without a redirect breaks existing direct navigation. After this ships, any bookmarked or already-open /preferences URL will 404 because src/app/(app)/preferences/page.tsx is gone and there is no redirect in middleware or next.config. Please keep a lightweight redirect from /preferences to /profile, or ideally /profile?tab=preferences, so the old entry point continues to work.
